services:
  # Frontend Service (Angular)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: library-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    networks:
      - library-network
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  # Backend Service (Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: library-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - library-network
    environment:
      - FLASK_APP=corrected_app.py
      - FLASK_ENV=production
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - HOST=0.0.0.0
      - PORT=5000

networks:
  library-network:
    driver: bridge

volumes:
  library-data:
    driver: local

# Global configuration
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
